# Generated by Django 5.0.1 on 2024-01-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="article",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
