# Generated by Django 5.0.1 on 2024-01-21 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="article",
            name="topic",
            field=models.CharField(
                choices=[
                    ("gastronomy", "Gastronomia"),
                    ("locals", "Noclegi"),
                    ("travel", "Podróże"),
                    ("footRoute", "Trasy piesze"),
                    ("bikeRoute", "Trasy rowerowe"),
                    ("carRoute", "Trasy samochodwe"),
                ],
                max_length=20,
                verbose_name="Temat",
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tytuł")),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("gastronomy", "Gastronomia"),
                            ("locals", "Noclegi"),
                            ("travel", "Podróże"),
                            ("footRoute", "Trasy piesze"),
                            ("bikeRoute", "Trasy rowerowe"),
                            ("carRoute", "Trasy samochodwe"),
                        ],
                        max_length=20,
                        verbose_name="Temat",
                    ),
                ),
                ("summary", models.TextField(verbose_name="Skrót")),
                ("content", models.TextField(verbose_name="Tekst")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data ostatniej aktualizacji"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tytuł")),
                ("content", models.TextField(verbose_name="Tekst")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data ostatniej aktualizacji"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                        verbose_name="Artykuł",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
