# Generated by Django 5.0.1 on 2024-01-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcomment",
            name="article",
        ),
        migrations.AddField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
                verbose_name="Post",
            ),
            preserve_default=False,
        ),
    ]
